### ISSUE TITLE
Causes error messages in private channels

### ISSUE THREAD

**Issue by mgwalker** [mbland/slack-github-issues#2]
When this script is enabled and hubot is in a private channel, a reaction added to any message in that channel will cause an error message in Slack:

![screen shot 2017-01-19 at 9 30 58 am](https://cloud.githubusercontent.com/assets/1775733/22112807/f83a6202-de29-11e6-9a97-37275f738228.png)

Similarly for reactions to messages in a DM with the bot.  I've got a pair of PRs ready to submit to address these separately.  I need to add some tests around this before I submit anything, so it'll be a little bit!  😃

**Comment by mbland** [comment]
Closed by #3 and #4 and published in [v1.1.0](https://github.com/mbland/slack-github-issues/releases/tag/v1.1.0).
